Repository CA-G12/E-commerce-team5, pull requests merged in 2022-09, with the labels that each got.

#2 build the file structure relates #1
  .env.example
  .eslintrc.js
  .gitignore
  .prettierrc.json
  client/.eslintrc.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/index.js
  client/src/logo.svg
  package-lock.json
  package.json
  src/app.js
  src/controllers/index.js
  src/database/config/connection.js
  src/database/config/init.sql
  src/database/queries/index.js
  src/index.js
  src/middlewares/index.js
  src/router/index.js
  src/utils/index.js
  src/validation/index.js
  src/validation/signin.js
  src/validation/signup.js
Labels: done

#5 Create db schema
  .env.example
  src/database/config/init.sql
Labels: awaiting-review

#6 create the server
  client/package.json
  client/src/App.js
  package-lock.json
  src/app.js
  src/index.js
Labels: done

#13 Signup back end
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth/index.js
  src/controllers/auth/login.js
  src/controllers/auth/logout.js
  src/controllers/auth/signup.js
  src/controllers/index.js
  src/database/config/connection.js
  src/database/config/init.sql
  src/database/queries/index.js
  src/database/queries/users/addUser.js
  src/database/queries/users/checkExistance.js
  src/database/queries/users/index.js
  src/router/auth.js
  src/router/index.js
  src/utils/customizedServerErrors.js
  src/utils/hashPassword.js
  src/utils/index.js
  src/utils/signJWT.js
  src/validation/index.js
  src/validation/signup.js
Labels: awaiting-review

#17 9 make products query
  src/controllers/index.js
  src/controllers/products/getProducts.js
  src/database/queries/index.js
  src/database/queries/products/getProducts.js
  src/router/index.js
  src/router/products.js
Labels: approved

#19 Authorization middlewares
  client/src/App.js
  src/controllers/index.js
  src/middlewares/authorization.js
  src/middlewares/getLoggedData.js
  src/middlewares/index.js
  src/router/auth.js
  src/utils/index.js
  src/utils/verifyJWT.js
  src/validation/signin.js
Labels: awaiting-review

#20 10 cart routes
  .gitignore
  src/controllers/cart/addCart.js
  src/controllers/cart/deleteCart.js
  src/controllers/cart/getCart.js
  src/controllers/cart/index.js
  src/controllers/index.js
  src/database/config/init.sql
  src/database/queries/cart/addCart.js
  src/database/queries/cart/deleteCart.js
  src/database/queries/cart/getCart.js
  src/database/queries/cart/index.js
  src/database/queries/index.js
  src/router/cart.js
  src/router/index.js
Labels: approved

#26 fix some bugs realtes #25
  src/controllers/auth/login.js
  src/controllers/cart/addCart.js
  src/database/queries/users/checkExistance.js
  src/middlewares/authorization.js
  src/middlewares/getLoggedData.js
  src/router/cart.js
Labels: approved

#37 i added the global style variables
  client/src/global_style.css
Labels: approved

#38 fix the returned data from getting cart query
  client/src/Components/Cart/index.jsx
  client/src/Components/Cart/style.css
  src/controllers/cart/getCart.js
Labels: awaiting-review

#41 fix database schema realtes #40
  src/controllers/index.js
  src/controllers/products/getSingleProduct.js
  src/controllers/products/index.js
  src/database/queries/index.js
  src/database/queries/products/getProducts.js
  src/database/queries/products/getSingleProduct.js
  src/database/queries/products/index.js
  src/router/products.js
Labels: approved

#43 fix the getCart query relates #42
  src/controllers/cart/addCart.js
  src/controllers/cart/deleteCart.js
  src/controllers/cart/getCart.js
  src/database/queries/cart/getCart.js
  src/router/cart.js
Labels: awaiting-review

#44 33 create page header
  client/src/Components/header/index.jsx
  client/src/Components/header/style.css
Labels: approved

#46 29 product card
  client/src/App.js
  client/src/Components/ProductCard/index.jsx
  client/src/Components/ProductCard/style.css
  client/src/Components/Products/index.jsx
  client/src/Components/loginPage/index.jsx
  client/src/Components/signupPage/index.jsx
  client/src/global_style.css
  src/controllers/cart/addCart.js
  src/controllers/cart/getCart.js
  src/controllers/products/getSingleProduct.js
  src/database/config/init.sql
  src/database/queries/cart/getCart.js
Labels: awaiting-review

#49 Fixed login bug
  client/src/App.js
  client/src/Components/loginPage/index.jsx
Labels: awaiting-review

#50 added footer
  client/src/Components/footer/index.jsx
  client/src/Components/footer/style.css
Labels: awaiting-review

#45 fixing database
  client/src/Components/Cart/index.jsx
  client/src/Components/Cart/style.css
  client/src/Components/CartItem/index.jsx
  client/src/Components/CartItem/style.css
  package-lock.json
  package.json
  src/app.js
  src/controllers/cart/index.js
  src/controllers/cart/updateCart.js
  src/database/config/init.sql
  src/database/queries/cart/index.js
  src/database/queries/cart/updateCart.js
  src/database/queries/index.js
  src/router/cart.js
Labels: awaiting-review

#51 added landing page and
  client/src/Components/footer/style.css
  client/src/Components/landing/index.jsx
  client/src/Components/landing/style.css
Labels: awaiting-review

#52 Single product page
  client/src/App.js
  client/src/Components/ProductPage/index.jsx
  client/src/Components/ProductPage/style.css
Labels: awaiting-review

#60 create the react-router and handle its endpoints relates #53
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Cart/index.jsx
  client/src/Components/ProductPage/style.css
  client/src/Components/Products/index.jsx
  client/src/Components/header/index.jsx
  client/src/Components/landing/index.jsx
  client/src/Components/loginPage/index.jsx
  client/src/Components/loginPage/style.css
  client/src/Components/signupPage/index.jsx
  client/src/Components/signupPage/style.css
  client/src/index.js
  src/controllers/auth/login.js
Labels: awaiting-review

#64 create the search products query and its route relayes #62
  client/src/Components/Products/index.jsx
  src/controllers/index.js
  src/controllers/products/index.js
  src/controllers/products/searchProducts.js
  src/database/queries/index.js
  src/database/queries/products/index.js
  src/database/queries/products/searchProducts.js
  src/router/products.js
Labels: awaiting-review

#70 handle empty cart case
  client/src/Components/Cart/index.jsx
  client/src/Components/CartItem/EmptyCart.jsx
  client/src/Components/CartItem/index.jsx
Labels: awaiting-review

#72 71 handle delete cart
  client/src/Components/Cart/style.css
  client/src/Components/CartItem/index.jsx
  client/src/Components/CartItem/style.css
  client/src/Components/ProductCard/broken1.png
  client/src/Components/ProductCard/index.jsx
  client/src/Components/ProductCard/style.css
  client/src/Components/Products/index.jsx
Labels: awaiting-review

#73 Handle viewing product
  client/src/Components/ProductCard/index.jsx
  client/src/Components/ProductCard/style.css
  client/src/Components/ProductPage/index.jsx
  client/src/Components/ProductPage/style.css
  client/src/Components/Products/index.jsx
  client/src/Components/Products/styles.css
  client/src/global_style.css
  src/database/config/init.sql
Labels: awaiting-review

#75 69 pagination
  client/src/Components/Cart/index.jsx
  client/src/Components/ProductCard/index.jsx
  client/src/Components/Products/index.jsx
  client/src/Components/header/index.jsx
  client/src/Components/loadingSpinner/index.jsx
  client/src/Components/loadingSpinner/style.css
  client/src/Components/noSearchData/index.js
  client/src/Components/noSearchData/style.css
  client/src/Components/pageNotFound/index.js
  client/src/Components/pageNotFound/style.css
  client/src/Components/searchLoading/style.css
  client/src/Components/signupPage/index.jsx
  client/src/index.js
  package-lock.json
  src/controllers/auth/signup.js
  src/controllers/categories/getCategory.js
  src/controllers/index.js
  src/controllers/products/getProductsCount.js
  src/controllers/products/getProuductsByOffset.js
  src/controllers/products/index.js
  src/controllers/products/searchProducts.js
  src/database/queries/categories/getCategories.js
  src/database/queries/index.js
  src/database/queries/products/getProducts.js
  src/database/queries/products/getProductsByOffset.js
  src/database/queries/products/getProductsCount.js
  src/database/queries/products/index.js
  src/database/queries/products/searchProducts.js
  src/router/products.js
Labels: awaiting-review

#82 style the auth spinner realtes #81
  client/src/Components/loadingSpinner/style.css
  client/src/Components/loginPage/index.jsx
  client/src/Components/signupPage/index.jsx
Labels: awaiting-review

#84 change the empty crat style and handle the broken image in cart page
  client/src/Components/Cart/style.css
  client/src/Components/CartItem/EmptyCart.jsx
  client/src/Components/CartItem/index.jsx
  client/src/Components/CartItem/style.css
Labels: awaiting-review

#80 77 styling the header
  client/src/Components/header/index.jsx
  client/src/Components/header/style.css
Labels: approved

#100 Fixed an error in the schema
  README.md
  src/database/config/init.sql
Labels: fixed
